# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dV_zHKnqyI3vcBsrrEH2o1DiVLa88xLX
"""

import streamlit as st
import google.generativeai as genai
import json
import pandas as pd
from datetime import datetime, timedelta
import random
import io

# Page config
st.set_page_config(
    page_title="Task & Workflow Automation Agent",
    page_icon="🤖",
    layout="wide"
)

# Initialize session state
if "messages" not in st.session_state:
    st.session_state.messages = []
if "workflows" not in st.session_state:
    st.session_state.workflows = []
if "task_history" not in st.session_state:
    st.session_state.task_history = []

# Sidebar for API key and settings
with st.sidebar:
    st.title("⚙️ Configuration")
    api_key = st.text_input("Google Gemini API Key", type="password")

    st.divider()
    st.subheader("🔧 Automation Modules")

    modules = {
        "📊 Sheets & Data": st.checkbox("Sheets & Data", value=True),
        "📈 Reports": st.checkbox("Reports", value=True),
        "📑 Presentations": st.checkbox("Presentations", value=True),
        "👥 HR Workflows": st.checkbox("HR Workflows", value=True),
        "💰 Sales Automation": st.checkbox("Sales Automation", value=True),
        "💵 Finance Tasks": st.checkbox("Finance Tasks", value=True),
    }

    st.divider()
    st.subheader("📋 Recent Tasks")
    for task in st.session_state.task_history[-5:]:
        st.caption(f"✅ {task['name']} - {task['time']}")

# Configure Gemini
def configure_gemini(api_key):
    genai.configure(api_key=api_key)
    return genai.GenerativeModel('gemini-1.5-flash')

# Task execution functions
class AutomationAgent:
    def __init__(self, model):
        self.model = model

    def parse_intent(self, user_input):
        prompt = f"""Analyze this automation request and extract structured information.
        Request: "{user_input}"

        Return a JSON object with:
        - task_type: one of [sheet_update, report_generation, presentation_creation, hr_workflow, sales_task, finance_task]
        - action: specific action to perform
        - parameters: dict of relevant parameters
        - description: brief description of what will be done

        Return ONLY valid JSON, no markdown."""

        response = self.model.generate_content(prompt)
        try:
            return json.loads(response.text.strip().replace("```json", "").replace("```", ""))
        except:
            return {"task_type": "general", "action": "process", "parameters": {}, "description": user_input}

    def execute_sheet_update(self, params):
        # Simulated sheet update
        rows = params.get("rows", random.randint(10, 100))
        cols = params.get("columns", ["Name", "Value", "Status", "Date"])

        data = {
            col: [f"Data_{i}" if col != "Date" else datetime.now().strftime("%Y-%m-%d")
                  for i in range(rows)] for col in cols
        }
        df = pd.DataFrame(data)
        return df, f"Updated {rows} rows across {len(cols)} columns"

    def generate_report(self, params):
        report_type = params.get("type", "summary")
        prompt = f"""Generate a professional {report_type} report with the following sections:
        1. Executive Summary
        2. Key Metrics (with sample numbers)
        3. Analysis
        4. Recommendations
        5. Next Steps

        Make it realistic and professional. Use markdown formatting."""

        response = self.model.generate_content(prompt)
        return response.text

    def create_presentation_outline(self, params):
        topic = params.get("topic", "Business Review")
        slides = params.get("slides", 10)

        prompt = f"""Create a {slides}-slide presentation outline for: {topic}

        For each slide provide:
        - Slide title
        - 3-4 bullet points
        - Speaker notes (1-2 sentences)

        Format as a structured outline with clear slide numbers."""

        response = self.model.generate_content(prompt)
        return response.text

    def hr_workflow(self, params):
        workflow_type = params.get("workflow", "onboarding")

        workflows = {
            "onboarding": [
                "✅ Create employee profile",
                "✅ Generate welcome email",
                "✅ Setup system accounts",
                "✅ Schedule orientation",
                "✅ Assign mentor",
                "✅ Create training plan"
            ],
            "offboarding": [
                "✅ Initiate exit process",
                "✅ Schedule exit interview",
                "✅ Revoke system access",
                "✅ Process final payroll",
                "✅ Transfer knowledge docs",
                "✅ Update org chart"
            ],
            "leave_request": [
                "✅ Validate leave balance",
                "✅ Check team coverage",
                "✅ Notify manager",
                "✅ Update calendar",
                "✅ Adjust workload"
            ]
        }

        return workflows.get(workflow_type, workflows["onboarding"])

    def sales_automation(self, params):
        task = params.get("task", "pipeline_update")

        # Generate sample sales data
        pipeline_data = pd.DataFrame({
            "Lead": [f"Company_{i}" for i in range(1, 11)],
            "Stage": random.choices(["Prospect", "Qualified", "Proposal", "Negotiation", "Closed"], k=10),
            "Value": [random.randint(10000, 100000) for _ in range(10)],
            "Probability": [random.randint(10, 90) for _ in range(10)],
            "Expected Close": [(datetime.now() + timedelta(days=random.randint(7, 90))).strftime("%Y-%m-%d") for _ in range(10)]
        })

        return pipeline_data

    def finance_task(self, params):
        task = params.get("task", "expense_report")

        expense_data = pd.DataFrame({
            "Category": ["Travel", "Software", "Marketing", "Office", "Utilities"],
            "Budget": [50000, 30000, 75000, 20000, 15000],
            "Actual": [random.randint(40000, 55000), random.randint(25000, 35000),
                      random.randint(60000, 80000), random.randint(15000, 25000),
                      random.randint(12000, 18000)],
            "Variance": [0, 0, 0, 0, 0]
        })
        expense_data["Variance"] = expense_data["Budget"] - expense_data["Actual"]

        return expense_data

# Main UI
st.title("🤖 Task & Workflow Automation Agent")
st.caption("Automate repetitive tasks across HR, Sales, Finance, and more")

# Quick action buttons
st.subheader("⚡ Quick Actions")
col1, col2, col3, col4 = st.columns(4)

with col1:
    if st.button("📊 Update Sheet", use_container_width=True):
        st.session_state.quick_action = "Update my sales tracking spreadsheet with latest data"
with col2:
    if st.button("📈 Generate Report", use_container_width=True):
        st.session_state.quick_action = "Generate a weekly sales performance report"
with col3:
    if st.button("👥 HR Onboarding", use_container_width=True):
        st.session_state.quick_action = "Start onboarding workflow for new employee"
with col4:
    if st.button("💰 Expense Report", use_container_width=True):
        st.session_state.quick_action = "Generate monthly expense report"

st.divider()

# Chat interface
st.subheader("💬 Automation Chat")

# Display chat history
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])
        if "data" in msg:
            st.dataframe(msg["data"])

# Chat input
if prompt := st.chat_input("Describe the task you want to automate..."):
    if not api_key:
        st.error("Please enter your Google Gemini API Key in the sidebar")
    else:
        # Add user message
        st.session_state.messages.append({"role": "user", "content": prompt})

        with st.chat_message("user"):
            st.markdown(prompt)

        # Process with agent
        with st.chat_message("assistant"):
            with st.spinner("🔄 Processing your request..."):
                try:
                    model = configure_gemini(api_key)
                    agent = AutomationAgent(model)

                    # Parse intent
                    intent = agent.parse_intent(prompt)

                    st.markdown(f"**🎯 Detected Task:** {intent['task_type'].replace('_', ' ').title()}")
                    st.markdown(f"**📝 Action:** {intent['description']}")

                    response_content = ""
                    response_data = None

                    # Execute based on task type
                    if intent['task_type'] == 'sheet_update':
                        df, msg = agent.execute_sheet_update(intent['parameters'])
                        response_content = f"✅ Sheet Update Complete!\n\n{msg}"
                        response_data = df
                        st.success(response_content)
                        st.dataframe(df)

                        # Download button
                        csv = df.to_csv(index=False)
                        st.download_button("📥 Download CSV", csv, "updated_sheet.csv", "text/csv")

                    elif intent['task_type'] == 'report_generation':
                        report = agent.generate_report(intent['parameters'])
                        response_content = f"✅ Report Generated!\n\n{report}"
                        st.markdown(report)

                    elif intent['task_type'] == 'presentation_creation':
                        outline = agent.create_presentation_outline(intent['parameters'])
                        response_content = f"✅ Presentation Outline Created!\n\n{outline}"
                        st.markdown(outline)

                    elif intent['task_type'] == 'hr_workflow':
                        steps = agent.hr_workflow(intent['parameters'])
                        response_content = "✅ HR Workflow Initiated!\n\n" + "\n".join(steps)
                        for step in steps:
                            st.markdown(step)

                    elif intent['task_type'] == 'sales_task':
                        df = agent.sales_automation(intent['parameters'])
                        response_content = "✅ Sales Pipeline Updated!"
                        response_data = df
                        st.success(response_content)
                        st.dataframe(df)

                    elif intent['task_type'] == 'finance_task':
                        df = agent.finance_task(intent['parameters'])
                        response_content = "✅ Finance Report Generated!"
                        response_data = df
                        st.success(response_content)
                        st.dataframe(df)

                        # Add variance analysis
                        total_variance = df["Variance"].sum()
                        status = "under budget ✅" if total_variance > 0 else "over budget ⚠️"
                        st.info(f"**Total Variance:** ${abs(total_variance):,.2f} {status}")

                    else:
                        # General task - use Gemini for response
                        general_prompt = f"Help with this automation task: {prompt}"
                        response = model.generate_content(general_prompt)
                        response_content = response.text
                        st.markdown(response_content)

                    # Save to history
                    msg_data = {"role": "assistant", "content": response_content}
                    if response_data is not None:
                        msg_data["data"] = response_data
                    st.session_state.messages.append(msg_data)

                    # Add to task history
                    st.session_state.task_history.append({
                        "name": intent['task_type'].replace('_', ' ').title(),
                        "time": datetime.now().strftime("%H:%M")
                    })

                except Exception as e:
                    st.error(f"Error: {str(e)}")

# Handle quick actions
if "quick_action" in st.session_state:
    action = st.session_state.quick_action
    del st.session_state.quick_action
    st.rerun()

# Workflow Builder Section
st.divider()
st.subheader("🔧 Workflow Builder")

with st.expander("Create Custom Workflow"):
    workflow_name = st.text_input("Workflow Name")

    col1, col2 = st.columns(2)
    with col1:
        trigger = st.selectbox("Trigger", [
            "Manual",
            "Schedule (Daily)",
            "Schedule (Weekly)",
            "On Event",
            "API Webhook"
        ])
    with col2:
        category = st.selectbox("Category", [
            "HR", "Sales", "Finance", "Operations", "Custom"
        ])

    steps = st.text_area("Workflow Steps (one per line)",
                         placeholder="Step 1: Fetch data from CRM\nStep 2: Process and validate\nStep 3: Update spreadsheet")

    if st.button("💾 Save Workflow"):
        if workflow_name and steps:
            workflow = {
                "name": workflow_name,
                "trigger": trigger,
                "category": category,
                "steps": steps.split("\n"),
                "created": datetime.now().strftime("%Y-%m-%d %H:%M")
            }
            st.session_state.workflows.append(workflow)
            st.success(f"Workflow '{workflow_name}' saved!")

# Display saved workflows
if st.session_state.workflows:
    st.subheader("📚 Saved Workflows")
    for i, wf in enumerate(st.session_state.workflows):
        with st.expander(f"🔄 {wf['name']} ({wf['category']})"):
            st.markdown(f"**Trigger:** {wf['trigger']}")
            st.markdown("**Steps:**")
            for step in wf['steps']:
                st.markdown(f"  • {step}")
            if st.button(f"▶️ Run Workflow", key=f"run_{i}"):
                st.info(f"Executing workflow: {wf['name']}...")

# Footer
st.divider()
st.caption("🤖 Powered by Google Gemini AI | Built with Streamlit")